name: Build container image

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY_URL: docker.io
  IMAGE_PREFIX: hanlinyang/
  IMAGE_NAME: tdstub

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Extract ref information
        uses: FranzDiebold/github-env-vars-action@v2
      - name: Prepare for container steps
        run: |
          docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} ${{ env.REGISTRY_URL }}
          echo "IMAGE_ID=${REGISTRY_URL}/${IMAGE_PREFIX}${IMAGE_NAME}" >> ${GITHUB_ENV}
      - name: Build image
        run: docker build -t "${IMAGE_ID}:latest" .
      - name: Push image to registry
        run: docker push "${IMAGE_ID}:latest"
      - name: Attach commit information
        run: |
          docker tag "${IMAGE_ID}:latest" "${IMAGE_ID}:${CI_REF_NAME_SLUG}"
          docker tag "${IMAGE_ID}:latest" "${IMAGE_ID}:${GITHUB_SHA}"
          docker push "${IMAGE_ID}:${CI_REF_NAME_SLUG}"
          docker push "${IMAGE_ID}:${GITHUB_SHA}"
