name: Deploy to cluster

on:
  workflow_run:
    workflows:
      - Build container image
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Retrive deployment configuration
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build-image.yml
          name: deployment-configuration
      - name: Set up Kubernetes context
        uses: azure/k8s-set-context@v1
        with:
          method: service-account
          k8s-url: https://k8s-api.services.infra.tree-diagram.site:6443
          k8s-secret: ${{ secrets.K8S_SERVICE_ACCOUNT_SECRET }}
      - name: Process deployment configuration
        run: |
          chmod -R u+x scripts/

          echo "::group::Deployment configuration"
          scripts/config.py get
          echo "::endgroup::"

          echo "::group::Extracting information from configuration"
          export GIT_COMMIT=$(scripts/config.py get git.commit)
          export GIT_REF=$(scripts/config.py get git.ref)
          export IMAGE=$(scripts/config.py get deploy.image)
          export CHANNEL=$(scripts/config.py get deploy.channel)
          export SERVICE_PORT=$(scripts/config.py get deploy.service-port)
          export MANIFESTS=$(scripts/config.py get deploy.manifests)
          echo "MANIFESTS=${MANIFESTS}" >> ${GITHUB_ENV}
          echo "::endgroup::"

          echo "::group::Processing manifests based on configuration"
          while IFS= read -r manifest; do
            echo "Processing $manifest"
            echo "$(envsubst < $manifest)" >$manifest
          done <<< "$MANIFESTS"
          echo "::endgroup::"
      - name: Deploy manifests
        uses: Azure/k8s-deploy@v1.3
        with:
          manifests: ${{ env.MANIFESTS }}
